#1
SELECT DEPT_CODE, MIN(BASIC) AS MINIMUM, MAX(BASIC) AS MAXIMUM, AVG(BASIC) AS AVERAGE FROM EMPLOYEE GROUP BY DEPT_CODE;
#2
SELECT DEPT_CODE, COUNT(EMP_CODE) AS FEMALES FROM EMPLOYEE WHERE SEX = 'F' GROUP BY DEPT_CODE;
#3
SELECT DEPT_CODE, CITY, COUNT(EMP_CODE) AS EMPLOYEES FROM EMPLOYEE GROUP BY DEPT_CODE, CITY;
#4
SELECT DEPT_CODE, DESIG_CODE, COUNT(*) AS NO_OF_EMPLOYEES FROM EMPLOYEE WHERE JN_DT > '2000-01-01' GROUP BY DEPT_CODE, DESIG_CODE ORDER BY NO_OF_EMPLOYEES ASC;
#5
SELECT DEPT_CODE, SUM(BASIC) AS TOTAL_BASIC FROM EMPLOYEE WHERE SEX='M' GROUP BY DEPT_CODE ORDER BY TOTAL_BASIC DESC; 
#6
SELECT EMP_NAME, DESIG_DESC, BASIC FROM EMPLOYEE NATURAL JOIN DESIGNATION;
#7
SELECT EMP_NAME, DESIG_DESC, DEPT_NAME, BASIC FROM EMPLOYEE, DESIGNATION, DEPARTMENT WHERE EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_CODE AND 
EMPLOYEE.DESIG_CODE = DESIGNATION.DESIG_CODE;
#8
SELECT DEPT_CODE FROM DEPARTMENT WHERE DEPT_CODE NOT IN (SELECT DEPT_CODE FROM EMPLOYEE);
#9
SELECT DEPT_NAME FROM EMPLOYEE NATURAL JOIN DEPARTMENT;
#10
SELECT DEPT_NAME FROM EMPLOYEE NATURAL JOIN DEPARTMENT GROUP BY DEPT_CODE HAVING COUNT(*) >= 4;
#11
SELECT DEPT_CODE FROM EMPLOYEE WHERE BASIC IN (SELECT MAX(BASIC) FROM EMPLOYEE);
#12
SELECT DESIG_DESC FROM EMPLOYEE NATURAL JOIN DESIGNATION WHERE BASIC IN (SELECT MAX(BASIC) FROM EMPLOYEE);
#13
SELECT DEPT_NAME, COUNT(*) AS NO_OF_MANAGERS FROM EMPLOYEE, DEPARTMENT, DESIGNATION WHERE EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_CODE AND
EMPLOYEE.DESIG_CODE = DESIGNATION.DESIG_CODE AND DESIGNATION.DESIG_DESC = 'MANAGER' GROUP BY DEPARTMENT.DEPT_CODE;
#14
SELECT DISTINCT BASIC AS MAX_BASIC FROM EMPLOYEE WHERE BASIC NOT IN (SELECT E1.BASIC FROM EMPLOYEE AS E1, EMPLOYEE AS E2
WHERE E1.BASIC < E2.BASIC);
#15
SELECT DISTINCT BASIC AS MIN_BASIC FROM EMPLOYEE WHERE BASIC NOT IN (SELECT E2.BASIC FROM EMPLOYEE AS E1, EMPLOYEE AS E2
WHERE E1.BASIC < E2.BASIC);
#16
#SUM
SELECT DEPT_NAME FROM (SELECT DEPT_NAME, SUM(BASIC) AS SUM FROM DEPARTMENT NATURAL JOIN EMPLOYEE GROUP BY DEPT_NAME) AS BASIC_DEPT 
WHERE SUM IN (SELECT MAX(SUM) FROM (SELECT DEPT_NAME, SUM(BASIC) AS SUM FROM DEPARTMENT NATURAL JOIN EMPLOYEE
GROUP BY DEPT_NAME)AS DEPT_BASIC);

#AVERAGE
SELECT DEPT_NAME FROM (SELECT DEPT_NAME, AVG(BASIC) AS AVG FROM DEPARTMENT NATURAL JOIN EMPLOYEE GROUP BY DEPT_NAME) AS BASIC_DEPT 
WHERE AVG IN (SELECT MAX(AVG) FROM (SELECT DEPT_NAME, AVG(BASIC) AS AVG FROM DEPARTMENT NATURAL JOIN EMPLOYEE
GROUP BY DEPT_NAME)AS DEPT_BASIC);

#EMP COUNT
SELECT DEPT_NAME FROM (SELECT DEPT_NAME, SUM(BASIC) AS SUM FROM DEPARTMENT NATURAL JOIN EMPLOYEE GROUP BY DEPT_NAME) AS BASIC_DEPT 
WHERE SUM IN (SELECT MAX(SUM) FROM (SELECT DEPT_NAME, SUM(BASIC) AS SUM FROM DEPARTMENT NATURAL JOIN EMPLOYEE
GROUP BY DEPT_NAME)AS DEPT_BASIC);

#17
INSERT INTO EMPLOYEE VALUES('E14','MADHAV','DP02','DS08','M','JADAVPUR','KOLKATA','WEST BENGAL','700032',0,'2013-10-28');
INSERT INTO EMPLOYEE VALUES('E15','ARYAN','DP03','DS09','M','JADAVPUR','KOLKATA','WEST BENGAL','700032',0,'2013-10-28');
INSERT INTO EMPLOYEE VALUES('E16','MEHRAN','DP05','DS06','M','IIT-D','NEW DELHI','NEW DELHI','700032',0,'2013-10-28');
INSERT INTO EMPLOYEE VALUES('E17','GAUTAM','DP01','DS08','M','JADAVPUR','KOLKATA','WEST BENGAL','700032',0,'2013-10-28');

#18
DELETE FROM EMPLOYEE WHERE DESIG_CODE NOT IN (SELECT DISTINCT DESIG_CODE FROM DESIGNATION);

#19
SELECT EMP_NAME FROM EMPLOYEE AS E1 WHERE BASIC > (SELECT AVG(BASIC) FROM EMPLOYEE AS E2 WHERE E1.DEPT_CODE=E2.DEPT_CODE) AND SEX = 'F';
#20
SELECT COUNT(*) AS NO_FEMALE_MANAGER FROM EMPLOYEE NATURAL JOIN DESIGNATION WHERE DESIG_DESC = 'MANAGER' AND SEX = 'F';

COMMIT;
