DROP TABLE BACKPAPER CASCADE;
DROP TABLE RESULT CASCADE;

CREATE TABLE RESULT(
	ROLL CHAR(10),
	SCODE CHAR(10),
	MARKS INT(16),
	PRIMARY KEY (ROLL, SCODE));

CREATE TABLE BACKPAPER(
	ROLL CHAR(10),
	SCODE CHAR(10));
	PRIMARY KEY(ROLL, SCODE);
	FOREIGN KEY(ROLL, SCODE) REFERENCES RESULT(ROLL, SCODE)

DELIMITER //

CREATE TRIGGER BACKPAPER_DELETE_TRIGGER
	BEFORE INSERT ON RESULT
	FOR EACH ROW BEGIN
		IF NEW.MARKS >= 50 THEN
			DELETE FROM BACKPAPER
				WHERE NEW.ROLL = ROLL
				AND NEW.SCODE = SCODE;
		END IF;
	END //

CREATE TRIGGER BACKPAPER_INSERT_TRIGGER
	AFTER INSERT ON RESULT
	FOR EACH ROW BEGIN
		IF NEW.MARKS < 50 THEN
			INSERT INTO BACKPAPER VALUES (
				NEW.ROLL,
				NEW.SCODE
			);
		END IF;
	END //

DELIMITER ;

CREATE TABLE REQUEST (
	REQ_NO INTEGER PRIMARY KEY,
	REQ_DT DATE
);

CREATE TABLE SERVICE_LOG (
	ENTRY_NO INTEGER PRIMARY KEY,
	REQ_CNT INTEGER,
	SERVICE_DT DATE
);

DELIMITER //

CREATE TRIGGER SERVICE_LOG_TRIGGER
	AFTER DELETE ON REQUEST
	FOR EACH ROW BEGIN
		IF  THEN

		END IF;
	END; //

DELIMITER ;
